name: Windroid CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Clone repository"
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: "set up JDK 17"
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: "set up Python 3"
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: "Get Branch Name"
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: "Grant execute permission for gradlew"
      run: chmod +x gradlew

    - name: "Build Debug"
      run: ./gradlew assembleDebug

    - name: "Sign APK"
      run: |
        if [ -n "${{ secrets.KEYSTORE_BASE64_MICEWINE }}" ]; then
          echo "${{ secrets.KEYSTORE_BASE64_MICEWINE }}" | base64 -d > micewine-key.jks
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign --ks micewine-key.jks --ks-key-alias "${{ secrets.KEYSTORE_ALIAS }}" --ks-pass "pass:${{ secrets.KEYSTORE_PASSWORD }}" --out Windroid-universal.apk app/build/outputs/apk/debug/app-universal-debug.apk
        else
          echo "Signing secret not found, skipping signing and using debug APK."
          cp app/build/outputs/apk/debug/app-universal-debug.apk Windroid-universal.apk
        fi

    - name: "Get Short SHA"
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: "Get Version"
      run: echo "VERSION=$(grep 'versionName' app/build.gradle | head -n 1 | sed 's/.*versionName[[:space:]=]*\"\([^"]*\)\".*/\1/')" >> $GITHUB_ENV
      
    - name: "Check If It's New Release"
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION_CHANGED=1" >> $GITHUB_ENV
        elif [ -n "$(git diff HEAD~1 HEAD app/build.gradle | grep versionName)" ]; then
          echo "VERSION_CHANGED=1" >> $GITHUB_ENV
        else
          echo "VERSION_CHANGED=0" >> $GITHUB_ENV
        fi
          
    - name: "Create Release"
      if: github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v2
      with:
        name: "Windroid Application (${{ env.VERSION }})"
        tag_name: ${{ env.SHORT_SHA }}
        prerelease: ${{ env.VERSION_CHANGED == '0' }}
        files: ./Windroid-universal.apk
    
    - name: "Upload Artifact"
      if: env.VERSION_CHANGED == '0' || github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: Windroid-Application-(git-${{ env.SHORT_SHA }})
        path: ./Windroid-universal.apk
